In [21]:
import pandas as pd
import numpy as np

In [22]:
# File to Load (Remember to Change These)
office_lines = "Resource/The-Office-Lines.csv"
office_dataset = "Resource/datasets_464222_984895_TheOfficeIMDBPerEpisode.csv"

In [23]:
# Read Student Data File and store into Pandas DataFrames
lines_df = pd.read_csv(office_lines)
dataset_df = pd.read_csv(office_dataset)

In [4]:
lines_df

,season,episode,title,speaker,line
0,1,1,Pilot,Michael,All right Jim. Your quarterlies look very good...
1,1,1,Pilot,Jim,"Oh, I told you. I couldn't close it. So..."
2,1,1,Pilot,Michael,So you've come to the master for guidance? Is ...
3,1,1,Pilot,Jim,"Actually, you called me in here, but yeah."
4,1,1,Pilot,Michael,"All right. Well, let me show you how it's done."
...,...,...,...,...,...
54622,9,24,Finale,Creed,It all seems so very arbitrary. I applied for ...
54623,9,24,Finale,Meredith,I just feel lucky that I got a chance to share...
54624,9,24,Finale,Phyllis,I'm happy that this was all filmed so I can re...
54625,9,24,Finale,Jim,I sold paper at this company for 12 years. My ...
54626,9,24,Finale,Pam,I thought it was weird when you picked us to m...

In [5]:
lines_df_title = lines_df.rename(columns={"title":"Title","season":"Season"})
lines_df_title

,Season,episode,Title,speaker,line
0,1,1,Pilot,Michael,All right Jim. Your quarterlies look very good...
1,1,1,Pilot,Jim,"Oh, I told you. I couldn't close it. So..."
2,1,1,Pilot,Michael,So you've come to the master for guidance? Is ...
3,1,1,Pilot,Jim,"Actually, you called me in here, but yeah."
4,1,1,Pilot,Michael,"All right. Well, let me show you how it's done."
...,...,...,...,...,...
54622,9,24,Finale,Creed,It all seems so very arbitrary. I applied for ...
54623,9,24,Finale,Meredith,I just feel lucky that I got a chance to share...
54624,9,24,Finale,Phyllis,I'm happy that this was all filmed so I can re...
54625,9,24,Finale,Jim,I sold paper at this company for 12 years. My ...
54626,9,24,Finale,Pam,I thought it was weird when you picked us to m...

In [6]:
lines_df_new = lines_df_title.copy()
lines_df_new

,Season,episode,Title,speaker,line
0,1,1,Pilot,Michael,All right Jim. Your quarterlies look very good...
1,1,1,Pilot,Jim,"Oh, I told you. I couldn't close it. So..."
2,1,1,Pilot,Michael,So you've come to the master for guidance? Is ...
3,1,1,Pilot,Jim,"Actually, you called me in here, but yeah."
4,1,1,Pilot,Michael,"All right. Well, let me show you how it's done."
...,...,...,...,...,...
54622,9,24,Finale,Creed,It all seems so very arbitrary. I applied for ...
54623,9,24,Finale,Meredith,I just feel lucky that I got a chance to share...
54624,9,24,Finale,Phyllis,I'm happy that this was all filmed so I can re...
54625,9,24,Finale,Jim,I sold paper at this company for 12 years. My ...
54626,9,24,Finale,Pam,I thought it was weird when you picked us to m...

In [7]:
lines_df_title = lines_df_new.groupby(["Title"])
lines_df_title.count()

                                  Season  episode  speaker  line
Title
A Benihana Christmas (Parts 1&2)     478      478      478   478
A.A.R.M                              501      501      501   501
After Hours                          335      335      335   335
Andy's Ancestry                      240      240      240   240
Andy's Play                          228      228      228   228
...                                  ...      ...      ...   ...
Welcome Party                        307      307      307   307
Whistleblower                        245      245      245   245
Women's Appreciation                 280      280      280   280
Work Bus                             314      314      314   314
s*x Ed                               313      313      313   313

[187 rows x 4 columns]

In [8]:
dataset_df

,Season,Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy
0,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels
1,1,Diversity Day,2005-03-29,8.3,4213,Michael's off color remark puts a sensitivity ...,Ken Kwapis,B. J. Novak
2,1,Health Care,2005-04-05,7.8,3536,Michael leaves Dwight in charge of picking the...,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,2005-04-12,8.1,3428,"Just for a laugh, Jim agrees to an alliance wi...",Bryan Gordon,Michael Schur
4,1,Basketball,2005-04-19,8.4,3745,Michael and his staff challenge the warehouse ...,Greg Daniels,Greg Daniels
...,...,...,...,...,...,...,...,...
183,9,Stairmageddon,2013-04-11,8.0,1743,Dwight shoots Stanley with a bull tranquilizer...,Matt Sohn,Dan Sterling
184,9,Paper Airplane,2013-04-25,8.0,1748,The employees hold a paper airplane competitio...,Jesse Peretz,Halsted Sullivan | Warren Lieberstein
185,9,Livin' the Dream,2013-05-02,9.0,2439,Dwight becomes regional manager after Andy qui...,Jeffrey Blitz,Niki Schwartz-Wright
186,9,A.A.R.M.,2013-05-09,9.5,3401,Dwight prepares for a marriage proposal and hi...,David Rogers,Brent Forrester
187,9,Finale,2013-05-16,9.8,9269,"One year later, Dunder Mifflin employees past ...",Ken Kwapis,Greg Daniels

In [9]:
dataset_df_title = dataset_df.groupby(["Title"])
dataset_df_title.count()

,Season,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy
Title,,,,,,,
A Benihana Christmas,1,1,1,1,1,1,1
A.A.R.M.,1,1,1,1,1,1,1
After Hours,1,1,1,1,1,1,1
Andy's Ancestry,1,1,1,1,1,1,1
Andy's Play,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...
Weight Loss,1,1,1,1,1,1,1
Welcome Party,1,1,1,1,1,1,1
Whistleblower,1,1,1,1,1,1,1
Women's Appreciation,1,1,1,1,1,1,1
Work Bus,1,1,1,1,1,1,1

In [10]:
dataset_df_title = dataset_df.rename(columns={"Title":"Title"})
dataset_df_title

,Season,Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy
0,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels
1,1,Diversity Day,2005-03-29,8.3,4213,Michael's off color remark puts a sensitivity ...,Ken Kwapis,B. J. Novak
2,1,Health Care,2005-04-05,7.8,3536,Michael leaves Dwight in charge of picking the...,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,2005-04-12,8.1,3428,"Just for a laugh, Jim agrees to an alliance wi...",Bryan Gordon,Michael Schur
4,1,Basketball,2005-04-19,8.4,3745,Michael and his staff challenge the warehouse ...,Greg Daniels,Greg Daniels
...,...,...,...,...,...,...,...,...
183,9,Stairmageddon,2013-04-11,8.0,1743,Dwight shoots Stanley with a bull tranquilizer...,Matt Sohn,Dan Sterling
184,9,Paper Airplane,2013-04-25,8.0,1748,The employees hold a paper airplane competitio...,Jesse Peretz,Halsted Sullivan | Warren Lieberstein
185,9,Livin' the Dream,2013-05-02,9.0,2439,Dwight becomes regional manager after Andy qui...,Jeffrey Blitz,Niki Schwartz-Wright
186,9,A.A.R.M.,2013-05-09,9.5,3401,Dwight prepares for a marriage proposal and hi...,David Rogers,Brent Forrester
187,9,Finale,2013-05-16,9.8,9269,"One year later, Dunder Mifflin employees past ...",Ken Kwapis,Greg Daniels

In [11]:
dataset_df_new = dataset_df_title.copy()
dataset_df_new

,Season,Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy
0,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels
1,1,Diversity Day,2005-03-29,8.3,4213,Michael's off color remark puts a sensitivity ...,Ken Kwapis,B. J. Novak
2,1,Health Care,2005-04-05,7.8,3536,Michael leaves Dwight in charge of picking the...,Ken Whittingham,Paul Lieberstein
3,1,The Alliance,2005-04-12,8.1,3428,"Just for a laugh, Jim agrees to an alliance wi...",Bryan Gordon,Michael Schur
4,1,Basketball,2005-04-19,8.4,3745,Michael and his staff challenge the warehouse ...,Greg Daniels,Greg Daniels
...,...,...,...,...,...,...,...,...
183,9,Stairmageddon,2013-04-11,8.0,1743,Dwight shoots Stanley with a bull tranquilizer...,Matt Sohn,Dan Sterling
184,9,Paper Airplane,2013-04-25,8.0,1748,The employees hold a paper airplane competitio...,Jesse Peretz,Halsted Sullivan | Warren Lieberstein
185,9,Livin' the Dream,2013-05-02,9.0,2439,Dwight becomes regional manager after Andy qui...,Jeffrey Blitz,Niki Schwartz-Wright
186,9,A.A.R.M.,2013-05-09,9.5,3401,Dwight prepares for a marriage proposal and hi...,David Rogers,Brent Forrester
187,9,Finale,2013-05-16,9.8,9269,"One year later, Dunder Mifflin employees past ...",Ken Kwapis,Greg Daniels

In [12]:
office_complete_df = pd.merge(dataset_df_new, lines_df_new, how="left", on=["Title","Season"])
office_complete_df.head()

,Season,Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy,episode,speaker,line
0,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Michael,All right Jim. Your quarterlies look very good...
1,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Jim,"Oh, I told you. I couldn't close it. So..."
2,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Michael,So you've come to the master for guidance? Is ...
3,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Jim,"Actually, you called me in here, but yeah."
4,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Michael,"All right. Well, let me show you how it's done."

In [13]:
office_complete_df.describe()

             Season        Rating     Num_Votes       episode
count  44863.000000  44863.000000  44863.000000  44837.000000
mean       5.565477      8.214531   2470.379934     12.590695
std        2.438122      0.551471   1027.923246      7.170938
min        1.000000      6.600000   1630.000000      1.000000
25%        3.000000      7.800000   1887.000000      6.000000
50%        6.000000      8.200000   2201.000000     12.000000
75%        8.000000      8.600000   2762.000000     19.000000
max        9.000000      9.800000   9269.000000     28.000000

In [14]:
lines_df_title = lines_df_new.groupby(["Title"])
lines_df_title.count()

                                  Season  episode  speaker  line
Title
A Benihana Christmas (Parts 1&2)     478      478      478   478
A.A.R.M                              501      501      501   501
After Hours                          335      335      335   335
Andy's Ancestry                      240      240      240   240
Andy's Play                          228      228      228   228
...                                  ...      ...      ...   ...
Welcome Party                        307      307      307   307
Whistleblower                        245      245      245   245
Women's Appreciation                 280      280      280   280
Work Bus                             314      314      314   314
s*x Ed                               313      313      313   313

[187 rows x 4 columns]

In [15]:
lines_df_new["Title"] = lines_df_new["Title"].replace('A Benihana Christmas (Parts 1&2)', 'A Benihana Christmas')
lines_df_new["Title"] = lines_df_new["Title"].replace('A.A.R.M', 'A.A.R.M.')
lines_df_new["Title"] = lines_df_new["Title"].replace('Boys & Girls', 'Boys and Girls')
lines_df_new["Title"] = lines_df_new["Title"].replace('Classy Christmas (Parts 1&2)', 'Classy Christmas')
lines_df_new["Title"] = lines_df_new["Title"].replace('Dunder Mifflin Infinity (Parts 1&2)', 'Dunder Mifflin Infinity')
lines_df_new["Title"] = lines_df_new["Title"].replace('Fun Run (Parts 1&2)', 'Fun Run')
lines_df_new["Title"] = lines_df_new["Title"].replace('Goodbye, Toby (Parts 1&2)', 'Goodbye, Toby')
lines_df_new["Title"] = lines_df_new["Title"].replace('Launch Party (Parts 1&2)', 'Launch Party')
lines_df_new["Title"] = lines_df_new["Title"].replace('Lecture Circuit (Part 1)', 'Lecture Circuit: Part 1')
lines_df_new["Title"] = lines_df_new["Title"].replace('Lecture Circuit (Part 2)', 'Lecture Circuit: Part 2')
lines_df_new["Title"] = lines_df_new["Title"].replace('The Manager and the Salesman', 'Manager and Salesman')
lines_df_new["Title"] = lines_df_new["Title"].replace('The Michael Scott Paper Company', 'Michael Scott Paper Company')
lines_df_new["Title"] = lines_df_new["Title"].replace('Money (Parts 1&2)', 'Money')
lines_df_new["Title"] = lines_df_new["Title"].replace('The New Guys', 'New Guys')
lines_df_new["Title"] = lines_df_new["Title"].replace('Niagara (Parts 1&2)', 'Niagara)')
lines_df_new["Title"] = lines_df_new["Title"].replace('Niagara: Part 1', 'Niagara)')
lines_df_new["Title"] = lines_df_new["Title"].replace('Niagara: Part 2', 'Niagara)')
lines_df_new["Title"] = lines_df_new["Title"].replace('Search Committee (Parts 1&2)', 'Search Committee')
lines_df_new["Title"] = lines_df_new["Title"].replace('Stress Relief (Parts 1&2)', 'Stress Relief')
lines_df_new["Title"] = lines_df_new["Title"].replace('The Delivery (Parts 1&2)', 'The Delivery')
lines_df_new["Title"] = lines_df_new["Title"].replace('The Delivery: Part 1', 'The Delivery')
lines_df_new["Title"] = lines_df_new["Title"].replace('The Delivery: Part 2', 'The Delivery')
lines_df_new["Title"] = lines_df_new["Title"].replace('The Job (Parts 1&2)', 'The Job')
lines_df_new["Title"] = lines_df_new["Title"].replace('Weight Loss (Parts 1&2)', 'Weight Loss')
lines_df_new["Title"] = lines_df_new["Title"].replace('s*x Ed', 'Sex Ed')
lines_df_new["Title"] = lines_df_new["Title"].replace('WUPHF.com', 'WUPHF.com')

In [16]:
lines_df_title = lines_df_new.groupby(["Title"])
lines_df_title.count()

                      Season  episode  speaker  line
Title
A Benihana Christmas     478      478      478   478
A.A.R.M.                 501      501      501   501
After Hours              335      335      335   335
Andy's Ancestry          240      240      240   240
Andy's Play              228      228      228   228
...                      ...      ...      ...   ...
Weight Loss              499      499      499   499
Welcome Party            307      307      307   307
Whistleblower            245      245      245   245
Women's Appreciation     280      280      280   280
Work Bus                 314      314      314   314

[187 rows x 4 columns]

In [17]:
office_final_df = pd.merge(dataset_df_new, lines_df_new, how="left", on=["Title","Season"])
office_final_df.head()

,Season,Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy,episode,speaker,line
0,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Michael,All right Jim. Your quarterlies look very good...
1,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Jim,"Oh, I told you. I couldn't close it. So..."
2,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Michael,So you've come to the master for guidance? Is ...
3,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Jim,"Actually, you called me in here, but yeah."
4,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais |Stephen Merchant and Greg Daniels,1.0,Michael,"All right. Well, let me show you how it's done."

In [18]:
office_final_df.describe()

             Season        Rating     Num_Votes       episode
count  52678.000000  52678.000000  52678.000000  52671.000000
mean       5.494704      8.293419   2541.603459     12.501794
std        2.364381      0.577576   1049.816444      7.330578
min        1.000000      6.600000   1630.000000      1.000000
25%        3.000000      7.900000   1918.000000      6.000000
50%        6.000000      8.200000   2327.000000     12.000000
75%        7.000000      8.700000   2785.000000     19.000000
max        9.000000      9.800000   9269.000000     28.000000

In [19]:
dataset_df_new.to_csv("Resource/cleaned_imdb_dataset.csv")

In [20]:
lines_df_new.to_csv("Resource/cleaned_imdb_lines.csv")